### ISSUE TITLE
Make assets a separate module

### ISSUE THREAD

**Issue by Ali-RS** [Monkey-Droid/CrossPlatformModule#10]
Hi @Scrappers-glitch :)

To follow the JME standards, I recommend making `assets` a separate module that `game` module depends on it. This makes assets portable and separate from the codebase. 

Also, it might improve project build performance as it won't compile assets every time the `game` code gets updated.

When developing we can use `runtimeOnly files('assets')` dependency (which requires no building and runs fast) and when publishing we can change it back to `runtimeOnly project(':assets')`.

**Comment by Scrappers-glitch** [comment]
Hello @Ali-RS, i will look into this, thanks for suggestions !

**Comment by Ali-RS** [comment]
Please see this for an example
https://github.com/Simsilica/Examples/tree/master/sigem

**Comment by Scrappers-glitch** [comment]
Yeah, thank you, i got a better idea of the benefits from Paul's reply on forums...

**Comment by Ali-RS** [comment]
Note in Simsilica example the `assets` folder  is actually a gradle module I believe

https://github.com/Simsilica/Examples/blob/6ccd7a138fd948ac472793106780935b57e42657/sigem/build.gradle#L22-L34

it is like a build-file less subproject. See https://hub.jmonkeyengine.org/t/projects-template-without-sdk/35200/96?u=ali_rs

It seems just a bit cleaner! But I am fine with both approaches.

**Comment by Scrappers-glitch** [comment]
> guess.
> 
> https://github.com/Simsilica/Examples/blob/6ccd7a138fd948ac472793106780935b57e42657/sigem/build.gradle#L22-L34
> 
> it is like a build-file less subproject

Yeah, but my suggestion was to create a separate module with a build.gradle that configure it as a java project as this example but not on the same game module which I think will better, I will do a PR for the supposed change...
